os: Visual Studio 2017

platform: x64

configuration:
  - Debug
  - Optimized
  - Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version

install:
  - cmd: mkdir c:\projects\deps
  - cmd: cd c:\projects\deps 
  - cmd: curl -L -o ispc-v1.9.2-windows.zip https://downloads.sourceforge.net/project/ispcmirror/v1.9.2/ispc-v1.9.2-windows.zip
  - cmd: 7z x ispc-v1.9.2-windows.zip
  - cmd: set PATH=C:\projects\deps\ispc-v1.9.2-windows;%PATH%
  - cmd: ispc --version

before_build:
  - cmd: cd c:\projects\engine
  - cmd: if not exist "build" mkdir build
  - cmd: cd build
  - cmd: cmake.exe .. -G "Visual Studio 15 2017 Win64"

build:
  project: build/Engine.sln
